### ISSUE TITLE
Demo stopped working

### ISSUE THREAD

**Issue by noestreich** [phiresky/tv-show-ratings#10]
The hosted demo stopped working.
After accessing [the demo-site](https://phiresky.github.io/tv-show-ratings/), it starts loading the "Game of Thrones"-example, but does not complete and just displays: "Loading..."

Typing an other Series name results in the same issue. 

<img width="616" alt="Bildschirmfoto 2020-04-05 um 21 29 48" src="https://user-images.githubusercontent.com/309419/78508097-9789cb80-7784-11ea-883f-80cff8343886.png">

**Comment by phiresky** [comment]
This was because the webtorrent trackers were failing and should be fixed now
