### ISSUE TITLE
Improve search

### ISSUE THREAD

**Issue by garyking** [phiresky/tv-show-ratings#4]
Perhaps sort search results by those with the most overall show ratings on IMDb? When searching for short names, like `Lost` or `Heroes`, which are pretty popular shows, they appear at around the 20th result, rather than the first or second.

**Comment by phiresky** [comment]
Good idea. I had that before in the previous version, but the new version only loads the list of series titles for the search so I didn't have that information anymore. But I can probably readd it without increasing the amount of data downloaded too much.
