### ISSUE TITLE
Update the data

### ISSUE THREAD

**Issue by garyking** [phiresky/tv-show-ratings#7]
Seems like the data was last updated around April 2018? Please update it, if so. Does it have to be done manually, and is it time-consuming, so that's why it hasn't been updated in a while?

**Comment by phiresky** [comment]
I've updated the data. It's not time consuming, but automating it would probably not be a good idea since the data is retrieved from peers, so if there are many different versions of the data floating around the site becomes more unstable.

**Comment by ghost** [comment]
another update would be great thanks

**Comment by phiresky** [comment]
done
